"""initial migration

Revision ID: 0c8507ad88f1
Revises: 
Create Date: 2025-08-05 21:56:45.043414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8507ad88f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recurring_meetings_id'), 'recurring_meetings', ['id'], unique=False)
    op.drop_constraint('recurring_meetings_ibfk_1', 'recurring_meetings', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_meetings', 'persons', ['leader_person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('report_attachments_ibfk_1', 'report_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'report_attachments', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('report_participants_ibfk_1', 'report_participants', type_='foreignkey')
    op.create_foreign_key(None, 'report_participants', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_reports_recurring_meeting', 'reports', type_='foreignkey')
    op.drop_constraint('reports_ibfk_1', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'persons', ['leader_person_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'recurring_meetings', ['recurring_meeting_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_ibfk_1', 'reports', 'persons', ['leader_person_id'], ['id'])
    op.create_foreign_key('fk_reports_recurring_meeting', 'reports', 'recurring_meetings', ['recurring_meeting_id'], ['id'])
    op.drop_constraint(None, 'report_participants', type_='foreignkey')
    op.create_foreign_key('report_participants_ibfk_1', 'report_participants', 'reports', ['report_id'], ['id'])
    op.drop_constraint(None, 'report_attachments', type_='foreignkey')
    op.create_foreign_key('report_attachments_ibfk_1', 'report_attachments', 'reports', ['report_id'], ['id'])
    op.drop_constraint(None, 'recurring_meetings', type_='foreignkey')
    op.create_foreign_key('recurring_meetings_ibfk_1', 'recurring_meetings', 'persons', ['leader_person_id'], ['id'])
    op.drop_index(op.f('ix_recurring_meetings_id'), table_name='recurring_meetings')
    # ### end Alembic commands ###
