"""add description field to recurring_meetings

Revision ID: 6871e6009940
Revises: 0c8507ad88f1
Create Date: 2025-08-05 22:09:58.229865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6871e6009940'
down_revision: Union[str, None] = '0c8507ad88f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_meetings', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_meetings', 'description')
    # ### end Alembic commands ###
